### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by GamerMJay** [IvanCraft623/RankSystem#71]
[CRITICAL] Malformed packet
#0 phar:///home/Server/SkyBlock/plugins/RankSystem_dev-69.phar/src/IvanCraft623/RankSystem/libs/poggit/libasynql/mysqli/MysqliThread.php(96): mysqli->ping()
#1 phar:///home/Server/SkyBlock/plugins/RankSystem_dev-69.phar/src/IvanCraft623/RankSystem/libs/poggit/libasynql/base/SqlSlaveThread.php(86): IvanCraft623\RankSystem\libs\poggit\libasynql\mysqli\MysqliThread->executeQuery(Object(mysqli), 3, 'SELECT * FROM R...', Array)
#2 phar:///home/Server/SkyBlock/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(109): IvanCraft623\RankSystem\libs\poggit\libasynql\base\SqlSlaveThread->onRun()
#3 [internal function]: pocketmine\thread\Thread->run()

![Bild_2023-09-23_150906393](https://github.com/IvanCraft623/RankSystem/assets/66413999/8929da78-513c-4a51-9f91-217b16af9ef1)

**Comment by GamerMJay** [comment]
please fix this
