### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kevincrafturu2** [IvanCraft623/RankSystem#87]
it suddenly crashes after loading the skins  

100 Skins were loadded!
Traceback (most recent call last):
  File "C:\Users\kevin\OneDrive\Escritorio\cs2_market_botX-main\cs2_market_botX-main\bot.py", line 97, in <module>
    asyncio.run(main())
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\kevin\OneDrive\Escritorio\cs2_market_botX-main\cs2_market_botX-main\bot.py", line 96, in main
    await run(playwright)
  File "C:\Users\kevin\OneDrive\Escritorio\cs2_market_botX-main\cs2_market_botX-main\bot.py", line 83, in run
    await inpt.fill(inspect_link)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_generated.py", line 15144, in fill
    await self._impl_obj.fill(
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_locator.py", line 205, in fill
    return await self._frame.fill(self._selector, strict=True, **params)
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_frame.py", line 527, in fill
    await self._channel.send("fill", locals_to_params(locals()))
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\kevin\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 513, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.fill: Timeout 30000ms exceeded.
Call log:
waiting for locator("#mat-input-1")

C:\Users\kevin\OneDrive\Escritorio\cs2_market_botX-main\cs2_market_botX-main>

**Comment by IvanCraft623** [comment]
Reported error doesn't have anything to do with RankSystem or even PocketMine-MP
